version: '3'
services:
  ccbot:
    image: langchain-streamlit-agent:latest
    build: ./app
    command: streamlit run main.py --server.port 8051
    volumes:
      - ./:/app/
    ports:
      - 8051:8051